package models

// This file includes the structs for the components specified in api.yml.
// Keep raw data type for struct creation and handle needed type in handlers and rules

// Receipt is a receipt that would be submitted for storing in memory
// ID will be generated from UUID in handlers; Others are expected in incoming JSON
type Receipt struct {
	ID           string `json:"id"`           // Unique identifier generated by google/uuid at handler
	Retailer     string `json:"retailer"`     // Name of retailer or store the receipt is from
	PurchaseDate string `json:"purchaseDate"` // Date of purchase on receipt in YYYY-MM-DD format
	PurchaseTime string `json:"purchaseTime"` // Time of purchase on receipt in 24 hour time format
	Items        []Item `json:"items"`        // Array list of Item component defined below
	Total        string `json:"total"`        // Total amount paid on receipt
}

// Item is a product purchased and will be stored in Receipt struct in an array
type Item struct {
	ShortDescription string `json:"shortDescription"` // Short product description for Item
	Price            string `json:"price"`            // Total price paid for Item
}

//TODO: Validation
